// <auto-generated />
using Infra.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Pergunta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataDeAtualizacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATA_DE_ATUALIZACAO");

                    b.Property<string>("DataDeCriacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATA_DE_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FOTO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("PERGUNTAS", "BACALHAU");
                });

            modelBuilder.Entity("Domain.Entities.Resposta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataDeAtualizacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATA_DE_ATUALIZACAO");

                    b.Property<string>("DataDeCriacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATA_DE_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FOTO");

                    b.Property<long>("PerguntaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PERGUNTA_ID");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("RESPOSTAS", "BACALHAU");
                });

            modelBuilder.Entity("Domain.Entities.Resposta", b =>
                {
                    b.HasOne("Domain.Entities.Pergunta", "Pergunta")
                        .WithMany("Respostas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("Domain.Entities.Pergunta", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
